# Generated by Django 6.0.2 on 2026-03-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
